language: go

go:
- 1.9

script:
- make test

jobs:
  include:
  - os: linux
  - stage: publish
    script:
    - export version=$(git describe --abbrev=0 --tags)
    - go get github.com/mitchellh/gox
    - go get github.com/tcnksm/ghr
    - gox -ldflags "-s -w -X github.com/voormedia/kd/cmd.version=${version}" -arch amd64 -os darwin -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
    - curl -O -L https://github.com/upx/upx/releases/download/v3.94/upx-3.94-amd64_linux.tar.xz && tar xf upx-3.94-amd64_linux.tar.xz
    - upx-3.94-amd64_linux/upx -9 dist/darwin_amd64_kd
    - ghr --username voormedia --token $GH_TOKEN --replace `git describe --tags` dist/
    os: linux

stages:
- name: test
- name: publish
  if: tag IS present

env:
  secure: AEcgMVWMDpZfMfWuJ8f5WaP44+aY1SPE+vCGA39993JlpR3+Te/jZT4mu1sCZ04xj1ccPV4D+vcu8eB/8mgzrvTnE3+16bfwoJjvqLQHbKE6hZStVC2Bgf995wfUkuRln09kn2NCOr1t5tT5HVeGgvkOVD4nUHlB6Ffe2tP2vVVTlTOTkkIFIVe4ptBSlbdRYRMJRZOt9AuidplSzYb/xCMOngtGma23K0TajzF0OEBpjtANWctKJHEw9oW7mjV23d/RtMJyLdaersKAdc5SMCJD0SXFWNCnrQSLwAZNE0E6rgnYutW4yYWQrrRVjPtHvPDbNZR/yjdyps/HLNDfN1Q4Et1pafqujcwoR6y/e9IYgsCoPJYqdgSyahbc5D4L3KRuKDH6svEzpeDjO+aHa6KmoiwITrUNKUIFE+C2DjneLIlznUMmzhY5N01O2yUiqo70OIw/azdhTNZnkEb22GGKM2FdMvADXayLEQFsDLUhve+CGn5GUmR3SmwluanQ/0SsfSBi9Rj8drvH51L64HeQwj66s5oxSMM0N/srhfYxmFit4C6C1TlRQYrebpnV9b8zVgoBawG56OkNy6iI7r/bw+NBs0ymdEVSRzZpTx06Js7hMWSrx9hPw+f8sNafOaoKAtId4Gx14NBrxwtZEAp/Fk48IAwbGlc/auephLU=
